;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        completion-at-point
        copy-rectangle-as-kill
        end-of-buffer
        evil-change
        evil-delete
        evil-force-normal-state
        indent-for-tab-command
        kill-region
        move-to-window-line-top-bottom
        org-self-insert-command
        python-nav-backward-block
        python-nav-forward-block
        ))

(setq mc/cmds-to-run-once
      '(
        ))
