;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        completion-at-point
        copy-rectangle-as-kill
        end-of-buffer
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-digit-argument-or-evil-beginning-of-line
        evil-find-char
        evil-force-normal-state
        evil-forward-word-begin
        evil-normal-state
        evil-previous-line
        evil-visual-char
        indent-for-tab-command
        kill-region
        move-to-window-line-top-bottom
        org-self-insert-command
        python-nav-backward-block
        python-nav-forward-block
        ))

(setq mc/cmds-to-run-once
      '(
        evil-forward-char
        evil-next-line
        evil-substitute
        evil-window-right
        helm-M-x
        ))
